### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by markheinmets** [markheinmets/Beeeeeebid#6]

**Comment by markheinmets** [comment]
![image](https://github.com/markheinmets/Beeeeeebid/assets/144334247/56b7d095-1509-4197-9824-bab79a4419ee)

**Comment by markheinmets** [comment]
![image](https://github.com/markheinmets/Beeeeeebid/assets/144334247/931fe647-853e-4ce9-8504-6e6da7d09651)

**Comment by Matlik-Official** [comment]
![Logo](https://github.com/markheinmets/Beeeeeebid/assets/63167163/a700c70b-3f4d-4885-a503-bca7d436b949)

**Comment by Matlik-Official** [comment]
![Logo_valge](https://github.com/markheinmets/Beeeeeebid/assets/63167163/e0d13edb-4e83-4581-a41c-3938931b37a4)
